### ISSUE TITLE
建议把 lin-cms-tp5-core和lin-cms-tp5-admin-code在lin-cms-tp5的README.md加个导航

### ISSUE THREAD

**Issue by luoyunchong** [ChenJinchuang/lin-cms-tp5#40]
建议把 lin-cms-tp5-core和lin-cms-tp5-admin-code在lin-cms-tp5的README.md加个导航，不然，在看源码时，不知道LinCmsTp5\admin\..的代码从哪里来，还找了好一会。

**Comment by ChenJinchuang** [comment]
前段时间这两个扩展一直在变化调整，所以没着急把这块写到README里去，接下来会有一波优化，会一并完善下这个问题。
PS：线上文档的开发文档栏目中就有涉及到这两个扩展的应用介绍

**Comment by luoyunchong** [comment]
另外问一下，lin-cms-flask  关于 admin 与core的内容是不是没有开源出来。多谢了

**Comment by ChenJinchuang** [comment]
> 另外问一下，lin-cms-flask 关于 admin 与core的内容是不是没有开源出来。多谢了

都是开源的，相关的源码都可以看得到，但是两个框架的实现方式和手段会有点点差异，需要自己稍微琢磨一下。

**Comment by luoyunchong** [comment]
@ChenJinchuang 好的，非常感谢，我再瞧瞧。
