### ISSUE TITLE
后台用户表nickname数据字段和代码中类属性不一致报错

### ISSUE THREAD

**Issue by vanwhebin** [ChenJinchuang/lin-cms-tp5#52]
![image](https://user-images.githubusercontent.com/8357785/68103117-82c4b580-ff10-11e9-844a-4e1680194481.png)

数据库中是nickname，vue前台传递的也是nickname
在lin-cms-tp5\admin-core\src\model\LinUser.php文件中

verify方法的用户查询字段为username
![image](https://user-images.githubusercontent.com/8357785/68103744-04b5de00-ff13-11e9-9b68-25e169d143a4.png)
返回记录日志也是nickname
![image](https://user-images.githubusercontent.com/8357785/68103920-b05f2e00-ff13-11e9-9a78-f8142dfaffdf.png)

修改：

只需要将数据库字段修改为username
以及在login方法中将36行日志记录的nickname改为username即可

另外需要在migration文件夹中重新生成数据表结构

nickname是昵称，字面意思还是用username更为合适

**Comment by ChenJinchuang** [comment]
这是由于lin-cms-vue 0.2.1版本调整了lin_user表字段引起的。你可能是在没有同步前后端仓库代码的情况下composer update了，目前扩展库是适配了0.2.1的所以会出现字段不一致的情况。仓库的代码已经同步适配（专栏内容还是0.2.0，会在开始前端内容章节时做一个升级指引）。

具体变动可以看lin-cms-vue 0.2.1更新日志。

推荐的同步最新代码的方式是git pull 同步代码，然后composer update更新扩展，然后重新运行php think migrate:run调整表结构，并手动到数据库中给原来的lin_user记录username字段添加一个值作为登陆账号，原来的nickname仅作为昵称不再是登陆账号了。
