### ISSUE TITLE
refresh_token 可以作为access_token使用，且永远不会过期。😱

### ISSUE THREAD

**Issue by chenggx** [ChenJinchuang/lin-cms-tp5#54]
![image](https://user-images.githubusercontent.com/16704288/68530640-0d5c4900-0345-11ea-9235-10e702cda199.png)

使用的是 master 分支，使用 refresh_token 作为access_token 来进行用户认证，可以通过。查看代码后发现两个 token 的生成方式是一样的。

**Comment by ChenJinchuang** [comment]
令牌的机制本来是打算重构一下封装成扩展包，因为一些不可描述的原因一直推迟。。这几天争取时间处理下。永不过期这个是我漏了。

**Comment by ChenJinchuang** [comment]
仓库推送了一个fix-token分支，可以拉取下在本地运行。

fix:refresh_token永不过期问题；
fix:refresh_token可以作为access_token来使用的问题，现在抛出一个异常信息
![image](https://user-images.githubusercontent.com/49727104/68538506-67debf00-03b0-11ea-92be-a6936d08ee2a.png)

欢迎测试。
