### ISSUE TITLE
注册用户接口，email 字段错误

### ISSUE THREAD

**Issue by chenggx** [ChenJinchuang/lin-cms-tp5#55]
![image](https://user-images.githubusercontent.com/16704288/68530783-80b28a80-0346-11ea-9a44-de58de007376.png)

![image](https://user-images.githubusercontent.com/16704288/68530757-4cd76500-0346-11ea-881d-6953f26444b5.png)

注册接口中，邮箱应该是可选字段，但是在创建用户的时候验证邮箱在表中是否唯一。没有根据参数进行判断，导致如果创建用户的时候没有填写邮箱就会报错。

![image](https://user-images.githubusercontent.com/16704288/68530803-dc7d1380-0346-11ea-99a6-88fa85e0ede7.png)

**Comment by chenggx** [comment]
不太会用 pull-request 😂就先提 issue 把

**Comment by chenggx** [comment]
我知道怎么回事了。因为在使用 Lin-CMS 前端项目的时候 email 字段传递的是空值，所以是可以成功的。我在 postman 上测试没有传递 email 字段。

在这里顺便问一下，那是在后台判断 email 是否存在好呢？还是就保持这样，跟前台沟通保证传递该字段呢？

**Comment by ChenJinchuang** [comment]
> 我知道怎么回事了。因为在使用 Lin-CMS 前端项目的时候 email 字段传递的是空值，所以是可以成功的。我在 postman 上测试没有传递 email 字段。
> 
> 在这里顺便问一下，那是在后台判断 email 是否存在好呢？还是就保持这样，跟前台沟通保证传递该字段呢？

问：那是在后台判断 email 是否存在好呢？还是就保持这样，跟前台沟通保证传递该字段呢？

答：更倾向沟通保证传递字段。但我想了想，人这东西最不靠谱了，后端还是要判断一下，为了复用，可以封装一个公共方法专门用来解析传递的字段，比如约定的可空字段没传，那就生成对应的字段并赋空值。

**Comment by chenggx** [comment]
好的，多谢解答。那我就先把 issue 关闭了。
