### ISSUE TITLE
lin-cms-vue上传图片加载失败

### ISSUE THREAD

**Issue by WangJianPi** [ChenJinchuang/lin-cms-tp5#62]
在lin-cms-vue-0.2.x 前端中有错误两处，
1、按十五章进行新增轮播图片设计时，增加图片后，无法加载显示图片。到lin-cms-tp5后端,在public/uploads/20200805目录中已经上传了图片。应该是返回前端的图片网址不准确。从开发者工具跟踪中，提示：get http://localhost/images/20200805/2349d1ad2993822d14acdf99d8ab1b6b.jpg 404(Not found)
2、选择lin-cms-vue-0.2.x的demo自定义组件中的upload图象上传页面，选择图片上传后，页面加载失败，提示：get  http://127.0.0.1:8000/uploads/20200805/755eb7e4710cc112d5999deb4eb60f7d.jpg   net::ERR_CONNECTION_REFUSED。注意，这里出现了127.0.0.1：8000。本人实际启动的是127.0.0.1:5000。这个127.0.0.1：8000是在那个文件中设置 的呢？

**Comment by ChenJinchuang** [comment]
按照课程的内容，会创建一个`config/setting.php`文件：
```php
return [
    'img_prefix' => 'http://localhost:5000/images',   // 图片url前缀配置
    'token_expire_in' => '7200'
];
```
修改这个`img_prefix`的值
